---
- name: Executing DNF
  register: dnf_results
  ansible.builtin.dnf:
    name: "{{ _servicename }}"
    state: "{{ _servicestate }}"

- name: Log dnf_results
  when: dnf_out is defined
  ansible.builtin.debug:
    var: dnf_results
    verbosity: 2
