---
- name: set hostname {{ inventory_hostname }}
  register: set_hostname_results
  ansible.builtin.hostname:
    name: "{{ inventory_hostname | regex_replace('_', '-') }}"

- name: Log set_hostname_results
  when: set_hostname_results is defined
  ansible.builtin.debug:
    var: set_hostname_results
    verbosity: 2
