---
- name: Pinging host {{ ansible_host }}
  register: pingme_results
  tags: "{{ _tags }}"
  ansible.builtin.ping:

- name: Log ping_results
  tags: "{{ _tags }}"
  when: ping_results is defined
  ansible.builtin.debug:
    var: pingme_results
