---
- name: Ping {{ inventory_hostname }}
  register: pingme_results
  ansible.builtin.ping:

- name: Log pingme_results
  when: pingme_results is defined
  ansible.builtin.debug:
    var: pingme_results
    verbosity: 2
