---
- name: Pinging host {{ inventory_hostname }}
  register: pingme_results
  tags:
    - create
  ansible.builtin.ping:

- name: Log ping_results
  tags:
    - create
  when: ping_results is defined
  ansible.builtin.debug:
    var: pingme_results
