---
- name: Pinging {{ inventory_hostname }}
  register: pingme_results
  tags:
    - create
  ansible.builtin.ping:

- name: Log pingme_results
  tags:
    - create
  when: ping_results is defined
  ansible.builtin.debug:
    var: pingme_results
