---
- name: Installing rhel-system-roles
  tags: always
  register: insights_dnf_output
  ansible.builtin.dnf:
    name: "{{ insights_packages }}"
    state: present

- name: Log insights_dnf_output
  tags: always
  when: dnf_out is defined
  ansible.builtin.debug:
    var: insights_dnf_output
    verbosity: 2

- name: Registering {{ inventory_hostname }}
  tags: create
  register: insights_output
  ansible.builtin.command: "rhc connect --organization {{ _org_id }} --activation-key {{ _activation_key }}"

- name: Unregistering {{ inventory_hostname }}
  tags: remove
  register: insights_output
  ansible.builtin.command: "insights-client --unregister"

- name: Log insights_output
  tags: always
  when: insights_output is defined
  ansible.builtin.debug:
    var: insights_output
    verbosity: 2
