---
- name: Ensure subscription-manager is installed
  tags: always
  ansible.builtin.dnf:
    name: subscription-manager
    state: present

- name: Registering system with Insights using activation key and organization ID
  tags: create
  hosts: localhost
  vars:
    rhc_auth:
      activation_keys:
        keys:
          - "{{ _activation_key }}"
     rhc_organization: "{{ _org_id }}"
  roles:
    - role: rhel-system-roles.rhc