# Ensure that subscription-manager is installed
# Depending on the tag [create = register host] [remove = unregister host]
---
- name: Ensure subscription-manager is installed
  tags: always
  ansible.builtin.dnf:
    name: subscription-manager
    state: present

- name: Register host {{ inventory_hostname }}
  tags: create
  register: rhsm_results
  community.general.redhat_subscription:
    activationkey: "{{ _activation_key }}"
    force_register: "{{ _force_register }}"
    org_id: "{{ _org_id }}"
    state: "{{ _state }}"
    syspurpose:
      usage: "{{ _usage }}"
      role: "{{ _systemrole }}"
      service_level_agreement: "{{ _service_level_agreement }}"
      sync: "{{ _sync }}"

- name: Unregister host {{ inventory_hostname }}
  tags: remove
  register: rhsm_results
  community.general.redhat_subscription:
    state: absent

- name: Log rhsm_results
  tags: always
  when: rhsm_results is defined
  ansible.builtin.debug:
    var: rhsm_results
    verbosity: 2
