---
- name: Ensure subscription-manager is installed
  tags: always
  ansible.builtin.dnf:
    name: subscription-manager
    state: present

- name: Block - Register host {{ inventory_hostname }}
  tags: create

  block:
    - name: Register host {{ inventory_hostname }}
      register: rhsm_results
      community.general.redhat_subscription:
        activationkey: "{{ _activation_key }}"
        force_register: "{{ _force_register }}"
        org_id: "{{ _org_id }}"
        state: "{{ _state }}"
        syspurpose:
          usage: "{{ _usage }}"
          role: "{{ _systemrole }}"
          service_level_agreement: "{{ _service_level_agreement }}"
          sync: "{{ _sync }}"

    - name: Log rhsm_results
      when: rhsm_results is defined
      ansible.builtin.debug:
        var: rhsm_results

- name: Block - Install subscription-manager & register host {{ inventory_hostname }}
  tags:
    - remove

  block:
    - name: Unregister host {{ inventory_hostname }}
      register: rhsm_results
      community.general.redhat_subscription:
        state: absent

    - name: Log rhsm_results
      when: rhsm_results is defined
      ansible.builtin.debug:
        var: rhsm_results
