---
# WIP
- name: Manage linux services
  hosts: "{{ _hosts }}"
  become: true
  gather_facts: false

  vars:
  # required
    servicename: 
    servicestate: latest
    # absent, installed, latest, present, removed
    autoremove: true
  # defaults
    verbose: false

  tasks:
    - name: Executing DNF Service
      ansible.builtin.dnf:
        name: "{{ servicename }}"
        state: "{{ servicestate }}"
      register: dnf_out

    - name: Log dnf_out
      ansible.builtin.debug:
        var: dnf_out
      when: verbose
