---
- name: Register Insights Client
  hosts: "{{ _hosts }}"
  become: true

  tasks:
    - name: Configure Red Hat insights
      ansible.builtin.import_role:
        name: redhat.insights.insights_client
      vars:  # noqa var-naming[no-role-prefix]
        insights_display_name: "{{ inventory_hostname }}"
        insights_tags:
          env: "{{ env }}"
          purpose: demo
          group: "{{ insights_tag }}"
