# Role: insights
# Ensure that subscription-manager is installed
# insights-client is installed
# Depending on the tag [create = register host] [remove = unregister host]
---
- name: Insights
  hosts: "{{ _hosts }}"
  become: true
  gather_facts: false

  roles:
    - role: insights