# Role: insights
# Ensure that subscription-manager, insights-client, rhel-system-roles are installed
# Depending on the tag [create = register host] [remove = unregister host]
---
- name: Insights Role
  hosts: "{{ _hosts }}"
  become: true
  gather_facts: false

  roles:
    - role: insights
