# Role: set_hostname
# use the set_hostname module to change a linux systems hostname
---
- name: set_hostname
  hosts: "{{ _hosts }}"
  become: true
  gather_facts: true

  roles:
      - set_hostname