# Role: subscription_mgr
# Ensure that subscription-manager is installed
# Depending on the tag [create = register host] [remove = unregister host]
---
- name: Subscription_mgr
  hosts: "{{ _hosts }}"
  become: true
  gather_facts: false

  roles:
    - role: subscription_mgr